services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"
    volumes:  # Persist the db data
      - database-data:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #   image: nextjs-dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - POSTGRES_URL=${DOCKER_POSTGRES_URL}
  #   links:
  #     - db
  #   depends_on:
  #     - db
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./src
  #         target: /app/src
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json

volumes:
  database-data: